"""FastAPI scoring service.

Exposes the pipeline's text-scoring machinery over HTTP:

  POST /score    — score arbitrary transcript text: uncertainty + LM tone
                   densities (negation-aware) for every derivable scope
                   (full text; Q&A section; executive-only answers;
                   CEO / CFO answers when a roster or intro attributes them)
  GET  /signals  — the latest out-of-sample hedging watchlist (one row per
                   ticker's most recent call, z-scored vs its own history)
  GET  /healthz  — liveness + lexicon sanity

Run locally:  uvicorn earnings_signals.api:app --reload
The service is stateless (lexicons load once at startup); CORS is open
because /score is a read-only demo endpoint over caller-supplied text.
"""

import csv
from importlib.metadata import PackageNotFoundError, version as pkg_version
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

from earnings_signals.exec_roles import exec_qa_by_role
from earnings_signals.lexicon import CONTROL_LOADERS, load_uncertainty_terms
from earnings_signals.qa_extract import extract_qa
from earnings_signals.qa_isolation import isolate_executive_qa
from earnings_signals.uncertainty import count_uncertainty

SIGNALS_CSV = Path(__file__).resolve().parent.parent / "results" / "latest_uncertainty_signals.csv"
MAX_TEXT_BYTES = 1_000_000  # one transcript is ~50KB; 1MB is generous

try:
    _VERSION = pkg_version("earnings-signals")
except PackageNotFoundError:  # running from a bare checkout
    _VERSION = "0.0.0+uninstalled"

_LEXICON = load_uncertainty_terms()
_CONTROLS = {cat: loader() for cat, loader in CONTROL_LOADERS.items()}


class ScoreRequest(BaseModel):
    text: str = Field(min_length=1, description="Transcript (or any) text to score")


class ScopeScore(BaseModel):
    total_tokens: int
    uncertainty_count: int
    negation_excluded: int
    uncertainty_density: float | None  # per 100 tokens; None for empty text
    tone_density: dict[str, float | None]  # negative/positive/litigious/constraining


class ScoreResponse(BaseModel):
    scopes: dict[str, ScopeScore]
    qa_isolated: bool
    exec_isolated: bool
    role_source: str | None  # "roster" | "intro" | None


class HealthResponse(BaseModel):
    status: str
    version: str
    lexicon_terms: int


app = FastAPI(
    title="Earnings Call NLP Risk Signals",
    description="Negation-aware Loughran-McDonald uncertainty scoring for "
    "earnings-call text, plus the latest hedging watchlist.",
    version=_VERSION,
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


def _score_scope(text: str) -> ScopeScore:
    r = count_uncertainty(text, _LEXICON)
    return ScopeScore(
        total_tokens=r.total_tokens,
        uncertainty_count=r.uncertainty_count,
        negation_excluded=r.negation_excluded,
        uncertainty_density=r.density,
        tone_density={
            cat: count_uncertainty(text, lex).density for cat, lex in _CONTROLS.items()
        },
    )


@app.post("/score", response_model=ScoreResponse)
def score(req: ScoreRequest) -> ScoreResponse:
    if len(req.text.encode("utf-8", errors="ignore")) > MAX_TEXT_BYTES:
        raise HTTPException(status_code=413, detail=f"text exceeds {MAX_TEXT_BYTES} bytes")

    scopes = {"full": _score_scope(req.text)}

    qa = extract_qa(req.text)
    if qa is not None:
        scopes["qa"] = _score_scope(qa)

    iso = isolate_executive_qa(req.text)
    if iso.mode == "exec_turns":
        scopes["execqa"] = _score_scope(iso.text)

    by_role, role_source = exec_qa_by_role(req.text)
    for role in ("ceo", "cfo"):
        role_text = (by_role or {}).get(role)
        if role_text:
            scopes[role] = _score_scope(role_text)

    return ScoreResponse(
        scopes=scopes,
        qa_isolated=qa is not None,
        exec_isolated=iso.mode == "exec_turns",
        role_source=role_source,
    )


@app.get("/signals")
def signals(limit: int = 25) -> list[dict[str, str]]:
    """Latest hedging watchlist, highest z-score first (as exported by
    scripts/latest_signals.py; regenerated by the weekly refresh)."""
    if not SIGNALS_CSV.exists():
        raise HTTPException(status_code=503, detail="watchlist not generated yet")
    limit = max(1, min(limit, 500))
    with SIGNALS_CSV.open(encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    return rows[:limit]


@app.get("/healthz", response_model=HealthResponse)
def healthz() -> HealthResponse:
    return HealthResponse(status="ok", version=_VERSION, lexicon_terms=len(_LEXICON))
