"""Generate web/data.js for the Uncertainty Explorer front end.

The explorer (web/index.html) reads exactly two exports from data.js:
``PANEL`` (headline panel constants) and ``getCompanies()`` returning
``[{ticker, name, quarters: [{label, density, eps}], r}]``. This script
replaces the mock's synthetic generator with the real series from
data/processed/tech_uncertainty_features.parquet.

Choices, kept consistent with scripts/analyze_uncertainty_growth.py:
- quarters shown are those with an isolated Q&A of >= 500 tokens (density
  on a tiny or unsplit Q&A is noise, so it is not displayed either);
- eps is next-quarter TTM EPS growth, winsorized at the same panel 1%/99%
  bounds as the analysis; the newest quarter has no outcome yet and is
  emitted as null (the chart renders the density bar without an EPS dot);
- per-company r is the Pearson correlation of the plotted pairs (so the
  number always matches what the viewer sees), null under 12 pairs.
"""

import json

import numpy as np
import pandas as pd

PARQUET = "data/processed/tech_uncertainty_features.parquet"
OUT = "web/data.js"

MIN_QA_TOKENS = 500
MIN_PAIRS_FOR_R = 12
WINSOR_PCT = 0.01

# Headline constants from results/uncertainty_growth_analysis.txt
PANEL = {
    "coefLow": -0.64,   # ticker + quarter FE
    "coefHigh": -0.89,  # ticker FE
    "n": 2773,
    "tickers": 72,
    "p": "< 0.02",
}


def main() -> None:
    df = pd.read_parquet(PARQUET)
    df = df[df["qa_isolated"] & (df["total_tokens_qa"] >= MIN_QA_TOKENS)].copy()
    df = df.sort_values(["ticker", "year", "quarter"])

    lo, hi = df["eps_ttm_growth_next_q"].quantile([WINSOR_PCT, 1 - WINSOR_PCT])
    df["eps_w"] = df["eps_ttm_growth_next_q"].clip(lo, hi)

    companies = []
    for ticker, g in df.groupby("ticker"):
        quarters = [
            {
                "label": f"Q{int(r.quarter)} '{int(r.year) % 100:02d}",
                "density": round(float(r.uncertainty_density_qa), 2),
                "eps": None if pd.isna(r.eps_w) else round(float(r.eps_w), 1),
            }
            for r in g.itertuples()
        ]
        pairs = g.dropna(subset=["eps_w"])
        r_val = (
            round(float(np.corrcoef(pairs["uncertainty_density_qa"], pairs["eps_w"])[0, 1]), 2)
            if len(pairs) >= MIN_PAIRS_FOR_R
            else None
        )
        companies.append({
            "ticker": ticker,
            "name": g["company"].iloc[-1],
            "quarters": quarters,
            "r": r_val,
        })

    body = (
        "// data.js — GENERATED by scripts/export_web_data.py from\n"
        f"// {PARQUET}. Do not edit by hand; rerun the script.\n"
        "// Interface contract: PANEL constants and getCompanies() ->\n"
        "//   [{ticker, name, quarters:[{label, density, eps|null}], r|null}]\n\n"
        f"export const PANEL = {json.dumps(PANEL, indent=2)};\n\n"
        f"const COMPANIES = {json.dumps(companies, separators=(',', ':'))};\n\n"
        "export function getCompanies() {\n  return COMPANIES;\n}\n"
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(body)
    n_q = sum(len(c["quarters"]) for c in companies)
    print(f"wrote {OUT}: {len(companies)} companies, {n_q} quarters, "
          f"eps winsorized at [{lo:.1f}, {hi:.1f}]")


if __name__ == "__main__":
    main()
